apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-ingress
spec:
  rules:
  - host: example.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: greeting-service
            port:
              number: 80