kind: Deployment
apiVersion: apps/v1
metadata:
  name: greeting-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: greeting-container
  template:
    metadata:
      labels:
        app: greeting-container
    spec:
      containers:
        - name: greeting-container
          image: localhost:5000/greeting-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          env:
          - name: secret_message_hello
            valueFrom:
              secretKeyRef:
                name: greeting-secret
                key: secret_message_hello_prop
          - name: secret_message_world
            valueFrom:
              secretKeyRef:
                name: greeting-secret
                key: secret_message_world_prop
          - name: secret_message_exclamation
            valueFrom:
              secretKeyRef:
                name: greeting-secret
                key: secret_message_exclamation_prop
      volumes:
      - name: secret-volume
        secret:
          secretName: greeting-secret
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: greeting-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
  selector:
    app: greeting-container