kind: Deployment
apiVersion: apps/v1
metadata:
  name: greeting-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-container
  template:
    metadata:
      labels:
        app: greeting-container
    spec:
      containers:
        - name: custom-text-service
          image: localhost:5000/custom-text-image
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 5
        - name: custom-greeting-service
          image: localhost:5000/custom-greeting-image
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
      restartPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: greeting-service
spec:
  type: NodePort
  ports:
    - name: greeting
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
    - name: text
      port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 32000
  selector:
    app: greeting-container